version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install reactjs-popup
  build:
    commands:
      - echo Building the application...
      - npm run build
      - ls -la # List all files in the root directory
      - ls -la build || echo "build directory not found" # Check for build directory
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: build
  discard-paths: no
