version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
    build:
      commands:
        - echo Building the application...
        - npm run build
        - ls -la # Add this to see what files/directories exist
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: build
